substitutions:
  tx_pin: "GPIO4"
  rx_pin: "GPIO2"
  
esphome:
  name: xy6020
  #friendly_name: xy6020l
  comment: "Monitor and control a xy6020 Digital Control Power Supply via UART-TTL"

#        Entsprechend die Daten Anpassen von dem zu verwendenden ESP 
esp32:
  board: nodemcu-32s

#              falls keine Weboberfläche vom ESP benötigt wird, auskommentiert lassen
#web_server:
#  port: 9005

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #manual_ip:
  #  static_ip: !secret xy6020_IP
  #  gateway: !secret gateway
  #  subnet: !secret subnet
  
  #ap:
  #  ssid: "xy6020 Fallback Hotspot"
  #  password: "UEikMwV1wqU8"


#       falls kein MQTT Broker verwendet wird auskommentiert lassen.
#  ! Warning     !!!!!!!!!!!!!!!!
#    If you enable MQTT and you do not use the “native API” for Home Assistant,
#    you must remove the api: line from your ESPHome configuration, otherwise the ESP will
#    reboot every 15 minutes because no client connected to the native API.
#mqtt:
#  broker: !secret mqtt_IP
#  port: 8883
#  username: !secret mqtt_user
#  password: !secret mqtt_password

ota:
  password: !secret xyota

api:
  encryption:
    key: !secret xykey

captive_portal:

logger:
  level: DEBUG

packages:
  remote_package:
    url: https://github.com/creepystefan/esphome-XY6020
    refresh: 0d
    files: [
      yml/sensors.yaml,
      yml/numbers.yaml,
      yml/switches.yaml,
      yml/text_senssor.yaml,
      yml/uart.yaml,
       ]



